import type { CatalogProduct } from '../../types'

export const FRESH_BOUQUETS: CatalogProduct[] = [
  {
    id: '1',
    name: 'Nuwara Eliya Crimson Empress',
    series: 'Grand Rose Collection',
    description: '36 long-stem velvet mountain roses curated with cinnamon quills and silver dollar eucalyptus.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3ohq50wAO2s5IZXu1cIEf4-RdSQp7bkpy-NZjh7W3h4EpwNozewmVLQey2ScYBVDdN2rqP1lSuiaOK9zGB8LhkEkXOvVXfqPPNEfp8nRcNNJa97hdycvt9CjfWvVt3gqYjeptjll4A6rzUbzMOfTUVMR7Tll2z2TVSr9h3Xfr_i3SNpL07i-Vi2YIZCCvT5qJ8gY3ulQGTUIIs0wMPRlqCx7yTqENIrGe-Pwnt-Kk5Mfnr8NzNYiN4Q',
    price: 18500,
    stemsLabel: '36 Highland Stems',
    badge: 'Signature Selection',
    note: 'Fresh Cut Today',
    noteTone: 'positive',
  },
  {
    id: '2',
    name: 'Highland Blush Symphony',
    series: 'Pastel Romance',
    description: 'Soft pink garden roses, ruffled white lisianthus, and cloud gypsophila in artisan pearl wrapping.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyQftHf58rcwEtPmCx9JHr2nFHRAgK8k2Hgea3-ozumimyLBZPV_33Ay2PKygTYORuIYEWaR10b0eNBV0TQnwJka75lbND3XI5OR0lQ9F3MicnJD_Z6yOg7ZKxV-KKcpSKl-Aei2AQ2forclrx0TBtJVLVNOgplOcUrs088YBBPHemRz6GHMb4vMf0PE8J2DSYiXMAjimlrkArWHOOXejqlsJSSu3NK6JNFYFyaJc36qZG7gM4VxUE6w',
    price: 15200,
    stemsLabel: '28 Highland Stems',
    note: 'Free Glass Vase',
  },
  {
    id: '3',
    name: 'Casablanca Pure Ivory Lilies',
    series: 'Oriental Lily Series',
    description: 'Multi-bud oriental lilies yielding up to 30 aromatic blossoms with tropical greenery.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnyVFNmZfHK5Ea9tTiWr5ORtFMFgzr0WhkL64m_zBG85ue6T0wK43EBeBb2s4LPvxrETqTxpGRLrcso5dTGRDQUrIeasYYnnv-BD_j0ef0nlavwTWzPs3S2Y58e3P2TdhAFGTYD51wSxFtezNRA8pbbw3GochDtfFW42Of4GEP8acXrWqvZeLWf2GyJrvkRXm9_jil0QROB-tw95bHb48dC9gOcYzKDWGtYakftpd1mzbJPnbgWWG9dQ',
    price: 19800,
    stemsLabel: '10 Multi-Bloom Stems',
    badge: 'Intensely Fragrant',
    note: 'Long 14-Day Vase Life',
    noteTone: 'positive',
  },
  {
    id: '4',
    name: 'Misty Blue Hydrangea',
    series: 'Cloud Flora',
    description: 'Sculptural, pillow-soft blue hydrangeas grown in Sri Lanka\'s cool central highlands.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6-Rhb2OjfEZsI-nR5vKA5SVFWqaA_MbUj75DKhE-WdB3VS2a85svj9bwTH__nDcR8grF-xmvMpY_2B2sj1Lu5xmPZUt8M1PQteVxfD9FOqUv-qa5u-pXOeN5cn5mBel-1EVAOqMKUJic6U1kLhKhcRtR5FAjPZgZxtLeDW3OxADFCqLR-IxmFV-opsBL_JdTFvzCW1EUVoz_9Dj7pipR0gWqRUJNOpQwaAJFl1tiRrhCboKT4t2ZUig',
    price: 16500,
    stemsLabel: '5 Giant Heads',
    badge: 'Rare Harvest',
    note: '3 Stems Left Today',
  },
  {
    id: '5',
    name: 'Golden Orchid Cascade',
    series: 'Tropical Splendor',
    description: 'Vibrant golden orchids cascading with tropical foliage — lasts up to three weeks indoors.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHTy9-9M-eLEakKabJmqt5zWWcDXxIZYvDfx6HTFrrAWQD33D6lvhOPxiCjPNxNzpUFQzK6dbnMLHlPcHUTKfiS-ux5HzC2TcZIb4Rj4deXn4gbLHNsBKWy34ep5fXDDaaP8gBhSLLWxZuw6qliv8vopsVyG4pMDSC4RCNluX5_XrNM1wjYGAUdVtE9MNCTpuByO72uPqEmTWbQCovqUOMjSr0A0gQHDSL3bR5u324kDpW7c3I1yaNOQ',
    price: 24000,
    stemsLabel: '22 Orchid Sprays',
    badge: 'Exotic Reserve',
    note: 'Includes Gift Crate',
    noteTone: 'positive',
  },
  {
    id: '6',
    name: 'Pastel Dawn Cottage Bunch',
    series: 'Wildflower Style',
    description: 'A relaxed, garden-gathered design of peach carnations, chamomile blossoms, and ferns.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgbK-b0XREStEbcvJ_lHOD3qrq4-kARyOjLhScvwfzWcY_gCSyXPWeHwwq-lNTSu63_-On3GZAKYPToy8kuXsLJ2_-qePwp6liyOhO7mpnCqN7e1dYlfcYQc6WyWevaH3yZnsRPL_x5C-X5e83Kre6mYTOijTDTrPvcLTXLedigD5tHaS6kRkj4V_UUvuSCTJoAQzwNikznCSptGXNcLErpZbolPeD1UsuoLId2MaO7re0kKdIaNGbMg',
    price: 13800,
    oldPrice: 15000,
    stemsLabel: '32 Wild & Spray Stems',
    note: '',
  },
  {
    id: '7',
    name: 'Velvet Rose & Eucalyptus Petite',
    series: 'Everyday Elegance',
    description: 'An intimate bunch of 18 hand-selected crimson roses framed with cooling blue eucalyptus.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBczUFB6mrXVfswOk3dxDdIodjbAJUGiXSPLwf4grgMZDBjfUS2mAQQjbeUF8SU-yapoEV0o0-AEXrlbOXOpcroGRfLnRNXYOc09_RC4aPMpEzJ9eUWLUCsZj2NZzFIa4HM8tPwmAoOKWvmA5EBElIOPR9U8mjxtXNr9w4OEJnz7bAWdz13dn9pEII_IWLLdTFxj8s-cOT6ZQGx7iNQh87hL8cABcoOFebqsUtqQ5YiN8D7doqq6wpbuQ',
    price: 9500,
    stemsLabel: '18 Highland Roses',
    note: 'Best Everyday Value',
    noteTone: 'positive',
  },
  {
    id: '8',
    name: 'Grand Botanical Collection',
    series: 'Ultra Luxury Edition',
    description: 'Our most distinguished arrangement — 60 premium stems combining garden roses, lilies and golden orchids, hand-delivered in a ceramic urn.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEMhv86bqAAIxQphaUMdz5j0HNu3HO_woBFXHx2PTjqSdYRqwkNAyBk1loaGmpULmN0WU3wBHLLXwcBl9vSx64SSvKYA-fm5km1OFH357wrSlC9JsP75OXtGIAmSj7DHttScUKa_EsuQxrrW-pWSKSqsZ0QV0IkYICaV6TFnM75XzxJcAn5PZbmqoPTVrAxa4sX8klzgNucO3fEXQpfwV3-xBnxrvHSlGthKsiDiIFesYXRjp79zrKkw',
    price: 32000,
    stemsLabel: '60 Stems Grandeur',
    note: '2 Made Daily',
    featured: true,
  },
]
